### ISSUE TITLE
How do I cycle outline visibility

### ISSUE THREAD

**Issue by khtan** [SeungukShin/org-code#2]
Hello,

I am an Emacs org-mode user and wanted to try your org-code extension. However, I do not see in your readme any information
about the cycling of tree visibility. In the native org-mode, entering Tab or Shift-Tab will cycle the tree visibility.
Is this not yet available in your extension? 

Thanks for making your code available!

**Comment by seungukshin** [comment]
Dear @khtan,

Folding feature is implemented, but key binding is not set.
You can fold / unfold your child using command palette (fold / unfold command) or mouse clock.
![image](https://user-images.githubusercontent.com/8279643/126053206-509d8f38-5566-49b1-93b1-32efb7296cfd.png)

Thank you.

**Comment by khtan** [comment]
Ah, now I see. This is not Emacs in Org-Mode, this is Org-Mode without Emacs. If tab is used to fold/unfold, then the user would not be able to type the "tab" character. There are some compromises then.
Thanks for your reply.
PS: I do not understand what is mouse clock but I do see that the '>' and 'V' icons on the left side that can be used to open each node, one at a time.

**Comment by seungukshin** [comment]
Dear @khtan,
> PS: I do not understand what is mouse clock but I do see that the '>' and 'V' icons on the left side that can be used to open each node, one at a time.
Sorry, it was my typo. "mouse clock" -> "mouse click"
