### ISSUE TITLE
Folding bug?

### ISSUE THREAD

**Issue by andreisilv** [SeungukShin/org-code#3]
![image](https://user-images.githubusercontent.com/56041659/146654213-270797f6-f5e8-4a93-b5d5-9ceb09a581d4.png)

Hi, just reporting a minor isssue, but the folding doesn't seem to be affecting my top level "Quick Reminders", that I would like to collapse so I can quickly see more important events. It's weird, but this other example works fine:

![image](https://user-images.githubusercontent.com/56041659/146654290-bcbbd6af-f98e-4853-b727-e021c4860412.png)

**Comment by seungukshin** [comment]
Dear @andrecc-7,
Thank you for reaching out to me.
You're right. It's a bug. Current version cannot detect a head line in the first line of the file.
It works properly if you insert dummy line before the `Quick reminders`, or you can try this one - [org-code-0.0.1.zip](https://github.com/SeungukShin/org-code/files/7776429/org-code-0.0.1.zip) which includes quick fix.
Thank you.

**Comment by andreisilv** [comment]
Thankyou, it's working!
